### ISSUE TITLE
[self.remoteView renderFrame:nil];

### ISSUE THREAD

**Issue by lkevin029** [sushilthe/webrtc-ios-swift#1]
how to call this [self.remoteView renderFrame:nil];
 on swift?

**Comment by ssldhl** [comment]
Inside `func appClient(client: ARDAppClient!, didReceiveRemoteVideoTrack remoteVideoTrack: RTCVideoTrack!)` do `remoteVideoTrack?.addRenderer(remoteView)`. `[self.remoteView renderFrame:nil]` is for objective-c, you can find the swift implementation in [WebRTCViewController](https://github.com/sushilthe/webrtc-ios-swift/blob/master/WebRTC%20iOS%20Swift/WebRTCViewController.swift).
